# Generated by Django 5.1 on 2024-08-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='total_fund',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
