# Generated by Django 5.1 on 2024-08-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_provider_total_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='total_fund',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
