# Generated by Django 5.1 on 2024-08-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=2),
        ),
    ]
