# Generated by Django 4.2.15 on 2024-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_rename_amount_loan_remaining_amount_loan_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=9), max_digits=9),
        ),
    ]
