# Generated by Django 4.2.15 on 2024-08-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_loanrequest'),
        ('bank', '0008_alter_loan_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_request',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.loanrequest'),
            preserve_default=False,
        ),
    ]
