# Generated by Django 5.1 on 2024-08-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_provider', '0003_alter_loan_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
