# Generated by Django 5.1 on 2024-08-24 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
